notes:
  - "该文件是打包后的代码，源代码请见 https://github.com/memset0/oi-helper qwq~"
domain:
  - www.luogu.org
  - www.luogu.com.cn
  - loj.ac
  - uoj.ac
  - vjudge.net
  - cn.vjudge.net
  - vjudge.z180.cn
  - szkopul.edu.pl
  - codeforces.com
  - codeforces.ml
  - codeforc.es
  - atcoder.jp
  - www.acmicpc.net
  - ioihw20.duck-ac.cn
tampermonkey:
  namespace: oi-helper
  require: []
  resource: []
  match:
    - https://github.com/memset0/oi-helper
  updateURL: https://cdn.jsdelivr.net/gh/memset0/oi-helper@dist/userscript.js
  downloadURL: https://cdn.jsdelivr.net/gh/memset0/oi-helper@dist/userscript.js
  grant:
    - unsafeWindow
    - GM_setValue
    - GM_getValue
    - GM_listValue
    - GM_deleteValue
    - GM_addStyle
    - GM_getResourceText