name: "Deploy to Artifacts"
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir dist
          npm install
          npm run build
      - name: Deploy
        uses: actions/upload-artifact@v1
        with:
          name: "oi-helper-${{ github.sha }}"
          path: dist/userscript.js